# Generated by Django 3.1.5 on 2021-01-31 13:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(blank=True, max_length=50)),
                ('num_card', models.CharField(blank=True, max_length=16)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('reg_date', models.DateField(default=django.utils.timezone.now)),
                ('gender', models.CharField(blank=True, choices=[('М', 'Male'), ('F', 'Female')], max_length=1)),
                ('language', models.CharField(blank=True, choices=[('UA', 'Ukrainian'), ('RU', 'Russian')], max_length=2)),
                ('phone', models.CharField(blank=True, max_length=10)),
                ('city', models.CharField(blank=True, max_length=50)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
