# Generated by Django 3.1.5 on 2021-02-15 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='gender',
            field=models.CharField(choices=[('Unknown', 'Unknown'), ('Male', 'Male'), ('Female', 'Female')], max_length=20),
        ),
        migrations.AlterField(
            model_name='client',
            name='language',
            field=models.CharField(choices=[('ENG', 'English'), ('UA', 'Ukrainian'), ('RU', 'Russian')], max_length=20),
        ),
    ]
