# Generated by Django 3.1.5 on 2021-02-13 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='language',
            field=models.CharField(choices=[('ENG', 'English'), ('UA', 'Ukrainian'), ('RU', 'Russian')], default=('ENG', 'English'), max_length=20),
        ),
    ]
