# Generated by Django 3.1.5 on 2021-02-15 06:31

from django.db import migrations, models
import django.utils.timezone
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0002_auto_20210215_0812'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='address',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='birth_date',
            field=models.DateField(default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='gender',
            field=models.CharField(choices=[('Unknown', 'Unknown'), ('Male', 'Male'), ('Female', 'Female')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='language',
            field=models.CharField(choices=[('ENG', 'English'), ('UA', 'Ukrainian'), ('RU', 'Russian')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='num_card',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=13, null=True, region=None, unique=True),
        ),
    ]
