# Generated by Django 3.1.5 on 2021-01-31 15:52

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('register', '0002_auto_20210131_1731'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Users',
            new_name='Client',
        ),
    ]
