# Generated by Django 3.1.5 on 2021-01-31 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0007_auto_20210131_2029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='gender',
            field=models.CharField(blank=True, choices=[('Мale', 'Male'), ('Female', 'Female')], max_length=10, null=True),
        ),
    ]
