# Generated by Django 3.1.5 on 2021-02-04 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0008_auto_20210131_2052'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='username',
            field=models.CharField(default='User.USERNAME_FIELD', max_length=50),
        ),
    ]
