# Generated by Django 3.1.5 on 2021-02-04 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0013_auto_20210204_1632'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='email',
            field=models.EmailField(max_length=50, null=True),
        ),
    ]
