# Generated by Django 3.1.5 on 2021-02-04 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0014_client_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='email',
        ),
        migrations.RemoveField(
            model_name='client',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='client',
            name='last_name',
        ),
        migrations.AlterField(
            model_name='client',
            name='language',
            field=models.CharField(blank=True, choices=[('UA', 'Ukrainian'), ('RU', 'Russian'), ('ENG', 'English')], max_length=3, null=True),
        ),
    ]
