# Generated by Django 3.1.5 on 2021-01-19 14:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Film',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default=' ', max_length=100)),
                ('country', models.CharField(default=' ', max_length=100)),
                ('genre', models.CharField(default=' ', max_length=200)),
                ('director', models.CharField(default=' ', max_length=65)),
                ('description', models.TextField(default=' ')),
                ('image', models.ImageField(help_text='Choose the picture of the film.', upload_to='films')),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(blank=True, max_length=50)),
                ('num_card', models.CharField(blank=True, max_length=16)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, choices=[('М', 'Male'), ('F', 'Female')], max_length=1)),
                ('language', models.CharField(blank=True, choices=[('UA', 'Ukrainian'), ('RU', 'Russian')], max_length=2)),
                ('phone', models.CharField(blank=True, max_length=15)),
                ('city', models.CharField(blank=True, max_length=50)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
