# Generated by Django 3.1.5 on 2021-02-13 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kino', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cinema',
            name='seo_description',
            field=models.TextField(blank=True, max_length=100),
        ),
    ]
