# Generated by Django 3.1.5 on 2021-02-18 10:45

from django.db import migrations, models
import django.db.models.fields.related


class Migration(migrations.Migration):

    dependencies = [
        ('kino', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cinemahallimage',
            name='image',
            field=models.FileField(upload_to='images/cinema_hall'),
        ),
        migrations.AlterField(
            model_name='cinemaimage',
            name='image',
            field=models.FileField(upload_to='images/cinema'),
        ),
        migrations.AlterField(
            model_name='filmimage',
            name='image',
            field=models.FileField(upload_to='images/film'),
        ),
        migrations.AlterField(
            model_name='newsimage',
            name='image',
            field=models.FileField(upload_to='images/news'),
        ),
        migrations.AlterField(
            model_name='sharesimage',
            name='image',
            field=models.FileField(upload_to='images/shares'),
        ),
        migrations.CreateModel(
            name='VipHallImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to='images/vip_hall')),
                ('vip_hall', models.ForeignKey(on_delete=django.db.models.fields.related.ForeignKey, to='kino.page')),
            ],
        ),
        migrations.CreateModel(
            name='ChildrenRoomImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to='images/children_room')),
                ('children_room', models.ForeignKey(on_delete=django.db.models.fields.related.ForeignKey, to='kino.page')),
            ],
        ),
        migrations.CreateModel(
            name='CafeBarImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to='images/cafe_bar')),
                ('cafe_bar', models.ForeignKey(on_delete=django.db.models.fields.related.ForeignKey, to='kino.page')),
            ],
        ),
    ]
