# Generated by Django 3.1.5 on 2021-02-11 12:20

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('kino', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='premiere',
            field=models.DateField(default=datetime.datetime(2021, 2, 11, 12, 20, 35, 552019, tzinfo=utc)),
        ),
    ]
