# Generated by Django 3.1.6 on 2021-02-17 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kino', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='backbanner',
            name='image',
            field=models.FileField(upload_to='banners/back'),
        ),
        migrations.AlterField(
            model_name='sharesbanner',
            name='image',
            field=models.FileField(upload_to='banners/shares'),
        ),
        migrations.AlterField(
            model_name='sliderbanner',
            name='image',
            field=models.FileField(upload_to='banners/slider'),
        ),
    ]
