# Generated by Django 3.1.5 on 2021-02-20 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kino', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='cost',
            field=models.CharField(default=0, max_length=25, null=True, verbose_name='Minimum cost:'),
        ),
    ]
