# Generated by Django 3.1.5 on 2021-01-18 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kino', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Film',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField(default=' ')),
                ('image', models.ImageField(help_text='Choose the picture of the film.', upload_to='films')),
            ],
        ),
    ]
