# Generated by Django 3.1.6 on 2021-02-09 21:49

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('kino', '0002_auto_20210209_2341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='premiere',
            field=models.DateField(default=datetime.datetime(2021, 2, 9, 21, 49, 14, 238471, tzinfo=utc)),
        ),
    ]
