# Generated by Django 3.1.5 on 2021-03-05 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kino', '0002_ads_halltype'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='imax',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='film',
            name='three_dimension',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='film',
            name='two_dimension',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
