# Generated by Django 3.1.5 on 2021-01-20 08:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kino', '0002_auto_20210120_1004'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FilmImages',
            new_name='FilmGallery',
        ),
        migrations.AlterModelOptions(
            name='filmgallery',
            options={'verbose_name_plural': 'FilmImages'},
        ),
    ]
