# Generated by Django 3.1.5 on 2021-02-20 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kino', '0002_schedule_cost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cinema',
            name='conditions',
            field=models.TextField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='cinema',
            name='description',
            field=models.TextField(blank=True, max_length=1000),
        ),
    ]
