# Generated by Django 3.1.5 on 2021-02-11 12:21

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('kino', '0002_auto_20210211_1420'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='premiere',
            field=models.DateField(default=datetime.datetime(2021, 2, 11, 12, 21, 53, 315853, tzinfo=utc)),
        ),
    ]
