# Generated by Django 3.1.5 on 2021-02-18 13:42

from django.db import migrations, models
import django.db.models.fields.related


class Migration(migrations.Migration):

    dependencies = [
        ('kino', '0002_auto_20210218_1245'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to='images/about')),
                ('about', models.ForeignKey(on_delete=django.db.models.fields.related.ForeignKey, to='kino.page')),
            ],
        ),
    ]
