# Generated by Django 3.1.5 on 2021-02-12 17:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kino', '0002_auto_20210212_1812'),
    ]

    operations = [
        migrations.CreateModel(
            name='CinemaHallImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to='images')),
                ('cinema_hall', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kino.cinemahall')),
            ],
        ),
    ]
