# Generated by Django 3.1.5 on 2021-02-11 12:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('kino', '0003_auto_20210211_1421'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='premiere',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
