# Generated by Django 3.1.5 on 2021-01-20 08:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kino', '0003_auto_20210120_1055'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='filmgallery',
            options={'verbose_name': 'FilmGallery', 'verbose_name_plural': 'FilmGallery'},
        ),
        migrations.RemoveField(
            model_name='filmgallery',
            name='post',
        ),
        migrations.AddField(
            model_name='filmgallery',
            name='Film',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='kino.film'),
        ),
    ]
