# Generated by Django 3.1.5 on 2021-02-20 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kino', '0003_auto_20210220_1618'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='description',
            field=models.TextField(default='', max_length=1000),
        ),
    ]
