# Generated by Django 3.1.6 on 2021-02-10 15:27

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('kino', '0004_auto_20210210_1724'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='premiere',
            field=models.DateField(default=datetime.datetime(2021, 2, 10, 15, 27, 44, 510570, tzinfo=utc)),
        ),
    ]
