# Generated by Django 3.1.5 on 2021-02-18 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kino', '0004_advertisingimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='music',
            field=models.CharField(default='', max_length=65, verbose_name='Music By:'),
        ),
        migrations.AlterField(
            model_name='film',
            name='scenarist',
            field=models.CharField(default='', max_length=65, verbose_name='Written By:'),
        ),
    ]
