# Generated by Django 3.1.5 on 2021-02-20 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kino', '0004_auto_20210220_1649'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='description',
            field=models.TextField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='shares',
            name='description',
            field=models.TextField(blank=True, max_length=1000),
        ),
    ]
