# Generated by Django 3.1.5 on 2021-02-12 20:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kino', '0004_auto_20210212_2001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cinemahall',
            name='preview',
            field=models.ImageField(upload_to='images'),
        ),
        migrations.AlterField(
            model_name='cinemahall',
            name='scheme',
            field=models.ImageField(upload_to='images'),
        ),
        migrations.CreateModel(
            name='NewsImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to='images')),
                ('news', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kino.cinemahall')),
            ],
        ),
    ]
