# Generated by Django 3.1.5 on 2021-02-11 12:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kino', '0004_auto_20210211_1422'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to='images')),
                ('film', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kino.film')),
            ],
        ),
    ]
