# Generated by Django 3.1.5 on 2021-01-20 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kino', '0004_auto_20210120_1059'),
    ]

    operations = [
        migrations.RenameField(
            model_name='filmgallery',
            old_name='Film',
            new_name='film',
        ),
    ]
