# Generated by Django 3.1.5 on 2021-03-05 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kino', '0005_film_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='duration',
            field=models.TimeField(error_messages={'invalid': 'Try to input duration in format HH:MM'}, null=True, verbose_name='Duration of film:'),
        ),
    ]
