# Generated by Django 3.1.6 on 2021-02-10 15:36

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('kino', '0005_auto_20210210_1727'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='premiere',
            field=models.DateField(default=datetime.datetime(2021, 2, 10, 15, 36, 55, 473457, tzinfo=utc)),
        ),
    ]
