# Generated by Django 3.1.5 on 2021-02-12 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kino', '0006_auto_20210212_2212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='news',
            name='status',
            field=models.CharField(choices=[('ON', 'On'), ('OFF', 'Off')], default=False, max_length=10),
        ),
    ]
