# Generated by Django 3.1.5 on 2021-02-21 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kino', '0006_auto_20210221_1910'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='film',
            name='genre',
        ),
        migrations.AddField(
            model_name='film',
            name='genre',
            field=models.CharField(choices=[('Sci-Fi', 'Sci-Fi'), ('Detective', 'Detective'), ('Horror', 'Horror')], max_length=50, null=True),
        ),
        migrations.DeleteModel(
            name='Genre',
        ),
    ]
