# Generated by Django 3.1.5 on 2021-01-20 09:24

from django.db import migrations, models
import django.db.models.deletion
from kino.models.cinema import *


class Migration(migrations.Migration):

    dependencies = [
        ('kino', '0006_auto_20210120_1102'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cinema',
            old_name='cinema_name',
            new_name='name',
        ),
        migrations.AlterField(
            model_name='film',
            name='country',
            field=models.CharField(default='', help_text='Страна съемки..', max_length=100),
        ),
        migrations.AlterField(
            model_name='film',
            name='director',
            field=models.CharField(default='', help_text='Режисер..', max_length=65),
        ),
        migrations.AlterField(
            model_name='film',
            name='genre',
            field=models.CharField(default='', help_text='Жанр..', max_length=200),
        ),
        migrations.CreateModel(
            name='CinemaGallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.FileField(upload_to=upload_cinema_gallery)),
                ('cinema', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='kino.cinema')),
            ],
            options={
                'verbose_name': 'FilmGallery',
                'verbose_name_plural': 'FilmGallery',
            },
        ),
    ]
