# Generated by Django 3.1.5 on 2021-02-18 18:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kino', '0006_schedule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='cinemahall',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='kino.cinemahall'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='film',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='kino.film'),
        ),
    ]
