# Generated by Django 3.1.5 on 2021-03-05 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kino', '0006_auto_20210305_1353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='duration',
            field=models.TimeField(null=True, verbose_name='Duration of film:'),
        ),
    ]
