# Generated by Django 3.1.5 on 2021-03-05 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kino', '0007_auto_20210305_1355'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='imax',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='schedule',
            name='three_dimensions',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='schedule',
            name='two_dimensions',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
