# Generated by Django 3.1.5 on 2021-01-20 09:34

from django.db import migrations, models
import django.db.models.deletion
import kino.models


class Migration(migrations.Migration):

    dependencies = [
        ('kino', '0007_auto_20210120_1124'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cinemagallery',
            options={'verbose_name': 'CinemaGallery', 'verbose_name_plural': 'CinemaGallery'},
        ),
        migrations.RenameField(
            model_name='cinemahall',
            old_name='cinemahall_name',
            new_name='name',
        ),
        migrations.CreateModel(
            name='CinemaHallGallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.FileField(upload_to=kino.models.upload_cinema_gallery)),
                ('hall', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='kino.cinemahall')),
            ],
            options={
                'verbose_name': 'CinemaHallGallery',
                'verbose_name_plural': 'CinemaHallGallery',
            },
        ),
    ]
