# Generated by Django 3.1.5 on 2021-02-19 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kino', '0002_auto_20210217_2229'),
        ('kino', '0007_auto_20210218_2056'),
    ]

    operations = [
    ]
