# Generated by Django 3.1.5 on 2021-02-21 18:27

from django.db import migrations, models
import django.db.models.fields.related


class Migration(migrations.Migration):

    dependencies = [
        ('kino', '0007_auto_20210221_1914'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='genre',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.CreateModel(
            name='MobileAppImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to='images/mobile_app')),
                ('mobile', models.ForeignKey(on_delete=django.db.models.fields.related.ForeignKey, to='kino.page')),
            ],
        ),
    ]
