# Generated by Django 3.1.5 on 2021-02-21 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kino', '0008_auto_20210221_2027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacts',
            name='address',
            field=models.TextField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='page',
            name='description',
            field=models.TextField(blank=True, max_length=500),
        ),
    ]
