# Generated by Django 3.1.5 on 2021-03-05 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kino', '0008_auto_20210305_1422'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HallType',
        ),
    ]
