# Generated by Django 3.1.5 on 2021-01-20 12:28

from django.db import migrations, models
import django.db.models.deletion
from kino.models.cinema import upload_cinemahall_gallery


class Migration(migrations.Migration):

    dependencies = [
        ('kino', '0008_auto_20210120_1134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cinemahall',
            name='cinema',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='kino.cinema'),
        ),
        migrations.AlterField(
            model_name='cinemahallgallery',
            name='images',
            field=models.FileField(upload_to=upload_cinemahall_gallery),
        ),
    ]
