# Generated by Django 3.1.5 on 2021-01-20 12:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kino', '0009_auto_20210120_1428'),
    ]

    operations = [
        migrations.AddField(
            model_name='cinemahallgallery',
            name='cinema',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='kino.cinema'),
        ),
    ]
