# Generated by Django 3.1.5 on 2021-02-22 07:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kino', '0009_auto_20210221_2039'),
    ]

    operations = [
        migrations.AddField(
            model_name='contacts',
            name='cinema',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='kino.cinema'),
        ),
    ]
