# Generated by Django 3.1.5 on 2021-01-20 12:50

from django.db import migrations, models
import kino.models


class Migration(migrations.Migration):

    dependencies = [
        ('kino', '0010_cinemahallgallery_cinema'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cinema',
            name='preview',
            field=models.ImageField(default='', help_text='Выберите превью к кинотеатру.', upload_to=kino.models.upload_cinema_preview),
        ),
    ]
