# Generated by Django 3.1.5 on 2021-02-22 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kino', '0010_contacts_cinema'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contacts',
            name='logo',
        ),
        migrations.RemoveField(
            model_name='contacts',
            name='name',
        ),
    ]
