# Generated by Django 3.1.5 on 2021-01-20 13:03

from django.db import migrations, models
from kino.models.cinema import upload_cinemahall_preview


class Migration(migrations.Migration):

    dependencies = [
        ('kino', '0011_auto_20210120_1450'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cinemahall',
            name='preview',
            field=models.ImageField(default='', help_text='Выберите превью к залу.', upload_to=upload_cinemahall_preview),
        ),
    ]
