# Generated by Django 3.1.5 on 2021-02-22 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kino', '0011_auto_20210222_0928'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacts',
            name='address',
            field=models.TextField(blank=True, max_length=200),
        ),
    ]
