# Generated by Django 3.1.5 on 2021-02-22 14:10

from django.db import migrations, models
import kino.models.cinema


class Migration(migrations.Migration):

    dependencies = [
        ('kino', '0012_auto_20210222_1051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cinemahall',
            name='description',
            field=models.TextField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='cinemahall',
            name='preview',
            field=models.ImageField(upload_to='images/preview'),
        ),
        migrations.AlterField(
            model_name='cinemahall',
            name='scheme',
            field=models.ImageField(upload_to=kino.models.cinema.upload_cinemahall_preview),
        ),
        migrations.AlterField(
            model_name='contacts',
            name='coordinates',
            field=models.FloatField(max_length=50),
        ),
    ]
