# Generated by Django 3.1.5 on 2021-01-20 13:12

from django.db import migrations, models
import kino.models


class Migration(migrations.Migration):

    dependencies = [
        ('kino', '0012_auto_20210120_1503'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='preview',
            field=models.ImageField(default='', help_text='Выберите превью к фильму.', upload_to=kino.models.upload_film_preview),
        ),
    ]
