# Generated by Django 3.1.5 on 2021-02-22 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kino', '0013_auto_20210222_1610'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacts',
            name='coordinates',
            field=models.CharField(max_length=50),
        ),
    ]
