# Generated by Django 3.1.5 on 2021-01-20 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kino', '0014_auto_20210120_1608'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client',
            options={'verbose_name': 'Клиент', 'verbose_name_plural': 'Клиенты'},
        ),
    ]
