# Generated by Django 3.1.5 on 2021-01-24 15:25

from django.db import migrations, models
from kino.models.film import current_year


class Migration(migrations.Migration):

    dependencies = [
        ('kino', '0015_auto_20210120_1620'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='music',
            field=models.CharField(default='', help_text='Music By..', max_length=65),
        ),
        migrations.AddField(
            model_name='film',
            name='producer',
            field=models.CharField(default='', help_text='Producer..', max_length=65),
        ),
        migrations.AddField(
            model_name='film',
            name='scenarist',
            field=models.CharField(default='', help_text='Written By..', max_length=65),
        ),
        migrations.AddField(
            model_name='film',
            name='year',
            field=models.IntegerField(choices=[(1984, 1984), (1985, 1985), (1986, 1986), (1987, 1987), (1988, 1988), (1989, 1989), (1990, 1990), (1991, 1991), (1992, 1992), (1993, 1993), (1994, 1994), (1995, 1995), (1996, 1996), (1997, 1997), (1998, 1998), (1999, 1999), (2000, 2000), (2001, 2001), (2002, 2002), (2003, 2003), (2004, 2004), (2005, 2005), (2006, 2006), (2007, 2007), (2008, 2008), (2009, 2009), (2010, 2010), (2011, 2011), (2012, 2012), (2013, 2013), (2014, 2014), (2015, 2015), (2016, 2016), (2017, 2017), (2018, 2018), (2019, 2019), (2020, 2020), (2021, 2021)], default=current_year, max_length=4),
        ),
        migrations.AlterField(
            model_name='film',
            name='country',
            field=models.CharField(default='', help_text='Country..', max_length=100),
        ),
        migrations.AlterField(
            model_name='film',
            name='director',
            field=models.CharField(default='', help_text='Director..', max_length=65),
        ),
        migrations.AlterField(
            model_name='film',
            name='genre',
            field=models.CharField(default='', help_text='Genre..', max_length=200),
        ),
        migrations.AlterField(
            model_name='film',
            name='name',
            field=models.CharField(default='', help_text='Name of movie', max_length=100),
        ),
    ]
