# Generated by Django 3.1.5 on 2021-02-22 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kino', '0015_auto_20210222_1826'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacts',
            name='coordinates',
            field=models.CharField(max_length=100),
        ),
    ]
