# Generated by Django 3.1.5 on 2021-01-24 16:14

from django.db import migrations, models
from kino.models.film import upload_film_preview


class Migration(migrations.Migration):

    dependencies = [
        ('kino', '0018_auto_20210124_1735'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='description',
            field=models.TextField(default='', help_text='Describe the plot of the film..'),
        ),
        migrations.AlterField(
            model_name='film',
            name='preview',
            field=models.ImageField(default='', help_text='Choose preview of the film..', upload_to=upload_film_preview),
        ),
    ]
