# Generated by Django 3.1.5 on 2021-01-25 08:31

from django.db import migrations, models
import kino.models


class Migration(migrations.Migration):

    dependencies = [
        ('kino', '0019_auto_20210124_1814'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='name',
            field=models.CharField(default='', max_length=100, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='film',
            name='preview',
            field=models.ImageField(default='', upload_to=kino.models.upload_film_preview),
        ),
    ]
