# Generated by Django 3.1.5 on 2021-01-26 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kino', '0020_auto_20210125_1031'),
    ]

    operations = [
        migrations.RenameField(
            model_name='filmgallery',
            old_name='images',
            new_name='image',
        ),
    ]
