# Generated by Django 3.1.5 on 2021-01-26 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kino', '0021_auto_20210126_1011'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='trailer',
            field=models.URLField(default='', help_text='Trailer URL'),
        ),
    ]
