# Generated by Django 3.1.5 on 2021-01-26 18:13

from django.db import migrations, models
import django.db.models.deletion
import kino.models


class Migration(migrations.Migration):

    dependencies = [
        ('kino', '0022_film_trailer'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=50)),
                ('pub_date', models.DateField()),
                ('description', models.TextField(default='')),
                ('preview', models.ImageField(default='', upload_to=kino.models.upload_news_preview)),
                ('status', models.BooleanField(default=False)),
            ],
        ),
        migrations.AlterModelOptions(
            name='cinema',
            options={},
        ),
        migrations.AlterModelOptions(
            name='cinemagallery',
            options={},
        ),
        migrations.AlterModelOptions(
            name='cinemahall',
            options={},
        ),
        migrations.AlterModelOptions(
            name='cinemahallgallery',
            options={},
        ),
        migrations.AlterModelOptions(
            name='client',
            options={},
        ),
        migrations.AlterModelOptions(
            name='film',
            options={},
        ),
        migrations.AlterModelOptions(
            name='filmgallery',
            options={},
        ),
        migrations.RenameField(
            model_name='cinemagallery',
            old_name='images',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='cinemahallgallery',
            old_name='images',
            new_name='image',
        ),
        migrations.AlterField(
            model_name='cinema',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='cinema',
            name='name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='cinema',
            name='preview',
            field=models.ImageField(default='', upload_to=kino.models.upload_cinema_preview),
        ),
        migrations.AlterField(
            model_name='cinemahall',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='cinemahall',
            name='name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='cinemahall',
            name='preview',
            field=models.ImageField(default='', upload_to=kino.models.upload_cinemahall_preview),
        ),
        migrations.AlterField(
            model_name='film',
            name='country',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='film',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='film',
            name='director',
            field=models.CharField(default='', max_length=65),
        ),
        migrations.AlterField(
            model_name='film',
            name='genre',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='film',
            name='music',
            field=models.CharField(default='', max_length=65),
        ),
        migrations.AlterField(
            model_name='film',
            name='producer',
            field=models.CharField(default='', max_length=65),
        ),
        migrations.AlterField(
            model_name='film',
            name='scenarist',
            field=models.CharField(default='', max_length=65),
        ),
        migrations.AlterField(
            model_name='film',
            name='trailer',
            field=models.URLField(default=''),
        ),
        migrations.AlterField(
            model_name='shares',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='shares',
            name='preview',
            field=models.ImageField(default='', upload_to='shares_and_disconts'),
        ),
        migrations.AlterField(
            model_name='shares',
            name='shares_name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.CreateModel(
            name='NewsGallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to=kino.models.upload_cinemahall_gallery)),
                ('news', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kino.news')),
            ],
            options={
                'verbose_name': 'News Gallery',
                'verbose_name_plural': 'News Gallery',
            },
        ),
    ]
