# Generated by Django 3.1.5 on 2021-01-26 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kino', '0023_auto_20210126_2013'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='newsgallery',
            options={},
        ),
        migrations.RenameField(
            model_name='shares',
            old_name='shares_name',
            new_name='name',
        ),
        migrations.AlterField(
            model_name='shares',
            name='preview',
            field=models.ImageField(default='', upload_to='upload_shares_preview'),
        ),
    ]
