# Generated by Django 3.1.5 on 2021-01-26 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kino', '0024_auto_20210126_2016'),
    ]

    operations = [
        migrations.AddField(
            model_name='shares',
            name='active_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='news',
            name='pub_date',
            field=models.DateField(null=True),
        ),
    ]
