# Generated by Django 3.1.5 on 2021-01-29 07:11

from django.db import migrations, models
import kino.models


class Migration(migrations.Migration):

    dependencies = [
        ('kino', '0025_auto_20210126_2020'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cinemahallgallery',
            name='cinema',
        ),
        migrations.RemoveField(
            model_name='cinemahallgallery',
            name='hall',
        ),
        migrations.RemoveField(
            model_name='filmgallery',
            name='film',
        ),
        migrations.RemoveField(
            model_name='newsgallery',
            name='news',
        ),
        migrations.AddField(
            model_name='cinema',
            name='image1',
            field=models.FileField(default='', upload_to=kino.models.upload_cinema_gallery),
        ),
        migrations.AddField(
            model_name='cinema',
            name='image2',
            field=models.FileField(default='', upload_to=kino.models.upload_cinema_gallery),
        ),
        migrations.AddField(
            model_name='cinema',
            name='image3',
            field=models.FileField(default='', upload_to=kino.models.upload_cinema_gallery),
        ),
        migrations.AddField(
            model_name='cinema',
            name='image4',
            field=models.FileField(default='', upload_to=kino.models.upload_cinema_gallery),
        ),
        migrations.AddField(
            model_name='cinema',
            name='image5',
            field=models.FileField(default='', upload_to=kino.models.upload_cinema_gallery),
        ),
        migrations.AddField(
            model_name='cinemahall',
            name='image1',
            field=models.FileField(default='', upload_to=kino.models.upload_cinemahall_gallery),
        ),
        migrations.AddField(
            model_name='cinemahall',
            name='image2',
            field=models.FileField(default='', upload_to=kino.models.upload_cinemahall_gallery),
        ),
        migrations.AddField(
            model_name='cinemahall',
            name='image3',
            field=models.FileField(default='', upload_to=kino.models.upload_cinemahall_gallery),
        ),
        migrations.AddField(
            model_name='cinemahall',
            name='image4',
            field=models.FileField(default='', upload_to=kino.models.upload_cinemahall_gallery),
        ),
        migrations.AddField(
            model_name='cinemahall',
            name='image5',
            field=models.FileField(default='', upload_to=kino.models.upload_cinemahall_gallery),
        ),
        migrations.AddField(
            model_name='film',
            name='image1',
            field=models.ImageField(default='', upload_to=kino.models.upload_film_gallery),
        ),
        migrations.AddField(
            model_name='film',
            name='image2',
            field=models.ImageField(default='', upload_to=kino.models.upload_film_gallery),
        ),
        migrations.AddField(
            model_name='film',
            name='image3',
            field=models.ImageField(default='', upload_to=kino.models.upload_film_gallery),
        ),
        migrations.AddField(
            model_name='film',
            name='image4',
            field=models.ImageField(default='', upload_to=kino.models.upload_film_gallery),
        ),
        migrations.AddField(
            model_name='film',
            name='image5',
            field=models.ImageField(default='', upload_to=kino.models.upload_film_gallery),
        ),
        migrations.AddField(
            model_name='news',
            name='image1',
            field=models.FileField(default='', upload_to=kino.models.upload_cinemahall_gallery),
        ),
        migrations.AddField(
            model_name='news',
            name='image2',
            field=models.FileField(default='', upload_to=kino.models.upload_cinemahall_gallery),
        ),
        migrations.AddField(
            model_name='news',
            name='image3',
            field=models.FileField(default='', upload_to=kino.models.upload_cinemahall_gallery),
        ),
        migrations.AddField(
            model_name='news',
            name='image4',
            field=models.FileField(default='', upload_to=kino.models.upload_cinemahall_gallery),
        ),
        migrations.AddField(
            model_name='news',
            name='image5',
            field=models.FileField(default='', upload_to=kino.models.upload_cinemahall_gallery),
        ),
        migrations.DeleteModel(
            name='CinemaGallery',
        ),
        migrations.DeleteModel(
            name='CinemaHallGallery',
        ),
        migrations.DeleteModel(
            name='FilmGallery',
        ),
        migrations.DeleteModel(
            name='NewsGallery',
        ),
    ]
