# Generated by Django 3.1.5 on 2021-01-29 17:29

from django.db import migrations, models
from kino.models.cinema import *
from kino.models.film import *


class Migration(migrations.Migration):

    dependencies = [
        ('kino', '0026_auto_20210129_0911'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shares',
            old_name='active_date',
            new_name='pub_date',
        ),
        migrations.RemoveField(
            model_name='film',
            name='trailer',
        ),
        migrations.AddField(
            model_name='cinema',
            name='conditions',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='cinema',
            name='logo',
            field=models.ImageField(blank=True, upload_to=upload_cinema_logo),
        ),
        migrations.AddField(
            model_name='cinema',
            name='seo_description',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='cinema',
            name='seo_keywords',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='cinema',
            name='seo_title',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='cinemahall',
            name='scheme',
            field=models.ImageField(blank=True, upload_to=upload_cinemahall_preview),
        ),
        migrations.AddField(
            model_name='cinemahall',
            name='seo_description',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='cinemahall',
            name='seo_keywords',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='cinemahall',
            name='seo_title',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='film',
            name='seo_description',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='film',
            name='seo_keywords',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='film',
            name='seo_title',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='film',
            name='video',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='news',
            name='seo_description',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='news',
            name='seo_keywords',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='news',
            name='seo_title',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='news',
            name='video',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='shares',
            name='image1',
            field=models.FileField(blank=True, upload_to=upload_cinemahall_gallery),
        ),
        migrations.AddField(
            model_name='shares',
            name='image2',
            field=models.FileField(blank=True, upload_to=upload_cinemahall_gallery),
        ),
        migrations.AddField(
            model_name='shares',
            name='image3',
            field=models.FileField(blank=True, upload_to=upload_cinemahall_gallery),
        ),
        migrations.AddField(
            model_name='shares',
            name='image4',
            field=models.FileField(blank=True, upload_to=upload_cinemahall_gallery),
        ),
        migrations.AddField(
            model_name='shares',
            name='image5',
            field=models.FileField(blank=True, upload_to=upload_cinemahall_gallery),
        ),
        migrations.AddField(
            model_name='shares',
            name='seo_description',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='shares',
            name='seo_keywords',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='shares',
            name='seo_title',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='shares',
            name='status',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='shares',
            name='video',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='cinema',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='cinema',
            name='image1',
            field=models.FileField(blank=True, upload_to=upload_cinema_gallery),
        ),
        migrations.AlterField(
            model_name='cinema',
            name='image2',
            field=models.FileField(blank=True, upload_to=upload_cinema_gallery),
        ),
        migrations.AlterField(
            model_name='cinema',
            name='image3',
            field=models.FileField(blank=True, upload_to=upload_cinema_gallery),
        ),
        migrations.AlterField(
            model_name='cinema',
            name='image4',
            field=models.FileField(blank=True, upload_to=upload_cinema_gallery),
        ),
        migrations.AlterField(
            model_name='cinema',
            name='image5',
            field=models.FileField(blank=True, upload_to=upload_cinema_gallery),
        ),
        migrations.AlterField(
            model_name='cinema',
            name='preview',
            field=models.ImageField(blank=True, upload_to=upload_cinema_preview),
        ),
        migrations.AlterField(
            model_name='cinemahall',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='cinemahall',
            name='image1',
            field=models.FileField(blank=True, upload_to=upload_cinemahall_gallery),
        ),
        migrations.AlterField(
            model_name='cinemahall',
            name='image2',
            field=models.FileField(blank=True, upload_to=upload_cinemahall_gallery),
        ),
        migrations.AlterField(
            model_name='cinemahall',
            name='image3',
            field=models.FileField(blank=True, upload_to=upload_cinemahall_gallery),
        ),
        migrations.AlterField(
            model_name='cinemahall',
            name='image4',
            field=models.FileField(blank=True, upload_to=upload_cinemahall_gallery),
        ),
        migrations.AlterField(
            model_name='cinemahall',
            name='image5',
            field=models.FileField(blank=True, upload_to=upload_cinemahall_gallery),
        ),
        migrations.AlterField(
            model_name='cinemahall',
            name='preview',
            field=models.ImageField(blank=True, upload_to=upload_cinemahall_preview),
        ),
        migrations.AlterField(
            model_name='film',
            name='image1',
            field=models.ImageField(blank=True, upload_to=upload_film_gallery),
        ),
        migrations.AlterField(
            model_name='film',
            name='image2',
            field=models.ImageField(blank=True, upload_to=upload_film_gallery),
        ),
        migrations.AlterField(
            model_name='film',
            name='image3',
            field=models.ImageField(blank=True, upload_to=upload_film_gallery),
        ),
        migrations.AlterField(
            model_name='film',
            name='image4',
            field=models.ImageField(blank=True, upload_to=upload_film_gallery),
        ),
        migrations.AlterField(
            model_name='film',
            name='image5',
            field=models.ImageField(blank=True, upload_to=upload_film_gallery),
        ),
        migrations.AlterField(
            model_name='film',
            name='preview',
            field=models.ImageField(blank=True, upload_to=upload_film_preview),
        ),
        migrations.AlterField(
            model_name='news',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='news',
            name='image1',
            field=models.FileField(blank=True, upload_to=upload_cinemahall_gallery),
        ),
        migrations.AlterField(
            model_name='news',
            name='image2',
            field=models.FileField(blank=True, upload_to=upload_cinemahall_gallery),
        ),
        migrations.AlterField(
            model_name='news',
            name='image3',
            field=models.FileField(blank=True, upload_to=upload_cinemahall_gallery),
        ),
        migrations.AlterField(
            model_name='news',
            name='image4',
            field=models.FileField(blank=True, upload_to=upload_cinemahall_gallery),
        ),
        migrations.AlterField(
            model_name='news',
            name='image5',
            field=models.FileField(blank=True, upload_to=upload_cinemahall_gallery),
        ),
        migrations.AlterField(
            model_name='news',
            name='preview',
            field=models.ImageField(blank=True, upload_to=upload_cinemahall_preview),
        ),
        migrations.AlterField(
            model_name='shares',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='shares',
            name='preview',
            field=models.ImageField(blank=True, upload_to=upload_cinemahall_preview),
        ),
    ]
