# Generated by Django 3.1.5 on 2021-01-29 18:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('kino', '0027_auto_20210129_1929'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='pub_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='shares',
            name='pub_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
