# Generated by Django 3.1.5 on 2021-01-29 18:30

from django.db import migrations, models
from kino.models.cinema import *


class Migration(migrations.Migration):

    dependencies = [
        ('kino', '0028_auto_20210129_2015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='image1',
            field=models.FileField(null=True, upload_to=upload_cinemahall_gallery),
        ),
        migrations.AlterField(
            model_name='news',
            name='image2',
            field=models.FileField(null=True, upload_to=upload_cinemahall_gallery),
        ),
        migrations.AlterField(
            model_name='news',
            name='image3',
            field=models.FileField(null=True, upload_to=upload_cinemahall_gallery),
        ),
        migrations.AlterField(
            model_name='news',
            name='image4',
            field=models.FileField(null=True, upload_to=upload_cinemahall_gallery),
        ),
        migrations.AlterField(
            model_name='news',
            name='image5',
            field=models.FileField(null=True, upload_to=upload_cinemahall_gallery),
        ),
        migrations.AlterField(
            model_name='news',
            name='preview',
            field=models.ImageField(null=True, upload_to=upload_cinemahall_preview),
        ),
    ]
