# Generated by Django 3.1.5 on 2021-01-30 14:50

from django.db import migrations, models
import kino.models


class Migration(migrations.Migration):

    dependencies = [
        ('kino', '0029_auto_20210129_2030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='image1',
            field=models.FileField(null=True, upload_to=kino.models.upload_news_gallery),
        ),
        migrations.AlterField(
            model_name='news',
            name='image2',
            field=models.FileField(null=True, upload_to=kino.models.upload_news_gallery),
        ),
        migrations.AlterField(
            model_name='news',
            name='image3',
            field=models.FileField(null=True, upload_to=kino.models.upload_news_gallery),
        ),
        migrations.AlterField(
            model_name='news',
            name='image4',
            field=models.FileField(null=True, upload_to=kino.models.upload_news_gallery),
        ),
        migrations.AlterField(
            model_name='news',
            name='image5',
            field=models.FileField(null=True, upload_to=kino.models.upload_news_gallery),
        ),
        migrations.AlterField(
            model_name='news',
            name='preview',
            field=models.ImageField(null=True, upload_to=kino.models.upload_news_preview),
        ),
        migrations.AlterField(
            model_name='shares',
            name='image1',
            field=models.FileField(blank=True, null=True, upload_to=kino.models.upload_cinemahall_gallery),
        ),
        migrations.AlterField(
            model_name='shares',
            name='image2',
            field=models.FileField(blank=True, null=True, upload_to=kino.models.upload_cinemahall_gallery),
        ),
        migrations.AlterField(
            model_name='shares',
            name='image3',
            field=models.FileField(blank=True, null=True, upload_to=kino.models.upload_cinemahall_gallery),
        ),
        migrations.AlterField(
            model_name='shares',
            name='image4',
            field=models.FileField(blank=True, null=True, upload_to=kino.models.upload_cinemahall_gallery),
        ),
        migrations.AlterField(
            model_name='shares',
            name='image5',
            field=models.FileField(blank=True, null=True, upload_to=kino.models.upload_cinemahall_gallery),
        ),
    ]
