# Generated by Django 3.1.5 on 2021-01-30 14:54

from django.db import migrations, models
from kino.models.cinema import upload_cinemahall_preview, upload_cinemahall_gallery


class Migration(migrations.Migration):

    dependencies = [
        ('kino', '0030_auto_20210130_1650'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shares',
            name='image1',
            field=models.FileField(default='', upload_to=upload_cinemahall_gallery),
        ),
        migrations.AlterField(
            model_name='shares',
            name='preview',
            field=models.ImageField(upload_to=upload_cinemahall_preview),
        ),
    ]
