# Generated by Django 3.1.5 on 2021-01-30 14:55

from django.db import migrations, models
from kino.models.cinema import upload_cinemahall_gallery


class Migration(migrations.Migration):

    dependencies = [
        ('kino', '0031_auto_20210130_1654'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shares',
            name='image1',
            field=models.FileField(blank=True, upload_to=upload_cinemahall_gallery),
        ),
    ]
