# Generated by Django 3.1.5 on 2021-01-30 15:13

from django.db import migrations, models
import kino.models


class Migration(migrations.Migration):

    dependencies = [
        ('kino', '0033_auto_20210130_1705'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='image1',
            field=models.ImageField(blank=True, null=True, upload_to=kino.models.upload_news_gallery),
        ),
        migrations.AlterField(
            model_name='news',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to=kino.models.upload_news_gallery),
        ),
        migrations.AlterField(
            model_name='news',
            name='image3',
            field=models.ImageField(blank=True, null=True, upload_to=kino.models.upload_news_gallery),
        ),
        migrations.AlterField(
            model_name='news',
            name='image4',
            field=models.ImageField(blank=True, null=True, upload_to=kino.models.upload_news_gallery),
        ),
        migrations.AlterField(
            model_name='news',
            name='image5',
            field=models.ImageField(blank=True, null=True, upload_to=kino.models.upload_news_gallery),
        ),
        migrations.AlterField(
            model_name='shares',
            name='image1',
            field=models.ImageField(blank=True, null=True, upload_to=kino.models.upload_shares_gallery),
        ),
    ]
