# Generated by Django 3.1.5 on 2021-02-04 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kino', '0038_auto_20210202_1730'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='status',
            field=models.BooleanField(choices=[('ON', 'True'), ('OFF', 'False')], default=False),
        ),
    ]
