# Generated by Django 3.1.5 on 2021-02-04 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kino', '0039_auto_20210204_1111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='status',
            field=models.CharField(blank=True, choices=[('ON', 'True'), ('OFF', 'False')], default=False, max_length=10),
        ),
    ]
