# Generated by Django 3.1.5 on 2021-02-04 17:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('kino', '0042_auto_20210204_1115'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='premiere',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
