# Generated by Django 3.1.5 on 2021-02-04 19:03

from django.db import migrations, models
import kino.models.film


class Migration(migrations.Migration):

    dependencies = [
        ('kino', '0043_film_premiere'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='image1',
            field=models.ImageField(upload_to=kino.models.film.upload_film_gallery),
        ),
        migrations.AlterField(
            model_name='film',
            name='image2',
            field=models.ImageField(upload_to=kino.models.film.upload_film_gallery),
        ),
        migrations.AlterField(
            model_name='film',
            name='image3',
            field=models.ImageField(upload_to=kino.models.film.upload_film_gallery),
        ),
        migrations.AlterField(
            model_name='film',
            name='image4',
            field=models.ImageField(upload_to=kino.models.film.upload_film_gallery),
        ),
        migrations.AlterField(
            model_name='film',
            name='image5',
            field=models.ImageField(upload_to=kino.models.film.upload_film_gallery),
        ),
        migrations.AlterField(
            model_name='film',
            name='preview',
            field=models.ImageField(upload_to=kino.models.film.upload_film_preview),
        ),
    ]
