# Generated by Django 3.1.5 on 2021-02-06 17:05

from django.db import migrations, models
import kino.models.film


class Migration(migrations.Migration):

    dependencies = [
        ('kino', '0044_auto_20210204_2103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='preview',
            field=models.FileField(upload_to=kino.models.film.upload_film_preview),
        ),
    ]
