# Generated by Django 3.1.5 on 2021-02-06 17:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kino', '0045_auto_20210206_1905'),
    ]

    operations = [
        migrations.AddField(
            model_name='cinemahall',
            name='created_date',
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
