# Generated by Django 3.1.6 on 2021-02-06 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kino', '0045_auto_20210206_1209'),
    ]

    operations = [
        migrations.CreateModel(
            name='BackBanner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='SharesBanner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('url', models.URLField()),
                ('spin_speed', models.IntegerField(default=5)),
            ],
        ),
        migrations.CreateModel(
            name='SliderBanner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('url', models.URLField()),
                ('text', models.TextField(blank=True)),
            ],
        ),
    ]
