# Generated by Django 3.1.5 on 2021-02-06 21:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kino', '0046_cinemahall_created_date'),
        ('kino', '0046_backbanner_sharesbanner_sliderbanner'),
    ]

    operations = [
    ]
