# Generated by Django 3.1.5 on 2021-02-09 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kino', '0047_merge_20210206_2300'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomePage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone1', models.CharField(blank=True, max_length=9, null=True)),
                ('phone2', models.CharField(blank=True, max_length=9, null=True)),
                ('seo_text', models.CharField(max_length=500)),
                ('seo_title', models.CharField(blank=True, max_length=50)),
                ('seo_keywords', models.CharField(blank=True, max_length=100)),
                ('seo_description', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.RenameModel(
            old_name='ContactModel',
            new_name='Contact',
        ),
        migrations.RenameModel(
            old_name='PageModel',
            new_name='Page',
        ),
        migrations.DeleteModel(
            name='HomePageModel',
        ),
    ]
