# Generated by Django 3.1.5 on 2021-02-09 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kino', '0048_auto_20210209_1147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='seo_text',
            field=models.TextField(max_length=500),
        ),
    ]
