# Generated by Django 3.1.5 on 2021-02-09 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kino', '0049_auto_20210209_1155'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Page',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='latitude',
            new_name='coordinates',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='longitude',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='pub_date',
        ),
    ]
