# Generated by Django 3.1.5 on 2021-02-09 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kino', '0050_auto_20210209_1647'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Contact',
            new_name='Contacts',
        ),
    ]
