# Generated by Django 3.1.5 on 2021-02-09 16:51

from django.db import migrations, models
import kino.models.shares


class Migration(migrations.Migration):

    dependencies = [
        ('kino', '0053_auto_20210209_1708'),
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=50)),
                ('description', models.TextField(blank=True)),
                ('status', models.BooleanField(default=False)),
                ('preview', models.ImageField(upload_to=kino.models.shares.upload_shares_preview)),
                ('image1', models.ImageField(blank=True, null=True, upload_to=kino.models.shares.upload_shares_gallery)),
                ('image2', models.ImageField(blank=True, null=True, upload_to=kino.models.shares.upload_shares_gallery)),
                ('image3', models.ImageField(blank=True, null=True, upload_to=kino.models.shares.upload_shares_gallery)),
                ('image4', models.ImageField(blank=True, null=True, upload_to=kino.models.shares.upload_shares_gallery)),
                ('image5', models.ImageField(blank=True, null=True, upload_to=kino.models.shares.upload_shares_gallery)),
                ('seo_title', models.CharField(blank=True, max_length=50)),
                ('seo_keywords', models.CharField(blank=True, max_length=100)),
                ('seo_description', models.CharField(blank=True, max_length=100)),
            ],
        ),
    ]
