# Generated by Django 3.1.5 on 2021-02-09 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kino', '0054_page'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='phone1',
            field=models.CharField(blank=True, max_length=13, null=True),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='phone2',
            field=models.CharField(blank=True, max_length=13, null=True),
        ),
    ]
